sim_name: "kubernetriks"
seed: 123

trace_config:
  generic_trace:
    workload_trace_path: src/data/generic_workload_trace_example.yaml
    cluster_trace_path: src/data/generic_cluster_trace_example.yaml

  # alibaba_cluster_trace_v2017:
  #   batch_instance_trace_path: /home/btkz/master/diploma/traces/alibaba-cluster-trace-v2017/batch_instance.csv
  #   batch_task_trace_path: /home/btkz/master/diploma/traces/alibaba-cluster-trace-v2017/batch_task.csv

default_cluster:
- node_template:
    metadata:
      name: super_node_256cpu_512gb
    status:
      capacity:
        cpu: 256000
        ram: 549755813888
- node_count: 10
  node_template:
    metadata:
      name: default_128cpu_256gb_node
    status:
      capacity:
        cpu: 64000
        ram: 274877906944
- node_count: 20
  node_template:
    metadata:
      name: default_64cpu_128gb_node
    status:
      capacity:
        cpu: 64000
        ram: 137438953472

scheduling_cycle_interval: 10.0

as_to_ps_network_delay: 0.050
ps_to_sched_network_delay: 0.089
sched_to_as_network_delay: 0.023
as_to_node_network_delay: 0.152
